title: Alex O'Connor
description: Software Developer
site_title: "Alex O'Connor"

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: AlexOConnorHub
# blog_url: https://www.nagekar.com
email: alex@alexoconnor.us
# keybase_username: abhn
# twitter_username: abhn_
# reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: G-DV7KBF8X05